package org.mfr.data;

// Generated 2011.09.19. 22:50:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Map;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.mfr.data.Photo;

/**
 * ExifData generated by hbm2java
 */
@Entity
@Table(name = "exif_data")
public class ExifData implements java.io.Serializable {

	private Integer id;
	private Photo photo;
	private String dateTimeOriginal;
	private Integer imageWidth;
	private Integer imageHeight;
	
	private Double fnumber;
	private String focalLength;
	private String exposureTime;	
	private Integer iso;
	
	private String exposureProgram;
	private String exposureCompenstation;
	private String meteringMode;
	private String whiteBalance;
	
	private String model;
	private String lensInfo;
	private String lensModel;
	private String lensMake;
	private Integer yresolution;
	private Integer xresolution;
	private String resolutionUnit;
	private String orientationDesc;
	

	public ExifData() {
	}

	public ExifData(Photo photo, Double fnumber, Integer iso, Integer imageWidth, Integer imageHeight,
			String exposureTime, String model, String exposureProgram, String dateTimeOriginal,
			String exposureCompenstation, String meteringMode, String whiteBalance, String lensInfo, String lensModel,
			String lensMake, Integer yresolution, Integer xresolution, String resolutionUnit, String orientationDesc,
			String focalLength) {
		this.photo = photo;
		this.fnumber = fnumber;
		this.iso = iso;
		this.imageWidth = imageWidth;
		this.imageHeight = imageHeight;
		this.exposureTime = exposureTime;
		this.model = model;
		this.exposureProgram = exposureProgram;
		this.dateTimeOriginal = dateTimeOriginal;
		this.exposureCompenstation = exposureCompenstation;
		this.meteringMode = meteringMode;
		this.whiteBalance = whiteBalance;
		this.lensInfo = lensInfo;
		this.lensModel = lensModel;
		this.lensMake = lensMake;
		this.yresolution = yresolution;
		this.xresolution = xresolution;
		this.resolutionUnit = resolutionUnit;
		this.focalLength = focalLength;
		this.orientationDesc = orientationDesc;
	}

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "photo")
	public Photo getPhoto() {
		return this.photo;
	}

	public void setPhoto(Photo photo) {
		this.photo = photo;
	}

	@Column(name = "fnumber", precision = 8, scale = 0)
	public Double getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(Double fnumber) {
		this.fnumber = fnumber;
	}

	@Column(name = "iso")
	public Integer getIso() {
		return this.iso;
	}

	public void setIso(Integer iso) {
		this.iso = iso;
	}

	@Column(name = "image_width")
	public Integer getImageWidth() {
		return this.imageWidth;
	}

	public void setImageWidth(Integer imageWidth) {
		this.imageWidth = imageWidth;
	}

	@Column(name = "image_height")
	public Integer getImageHeight() {
		return this.imageHeight;
	}

	public void setImageHeight(Integer imageHeight) {
		this.imageHeight = imageHeight;
	}

	@Column(name = "exposure_time", length = 0)
	public String getExposureTime() {
		return this.exposureTime;
	}

	public void setExposureTime(String exposureTime) {
		this.exposureTime = exposureTime;
	}

	@Column(name = "model", length = 0)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "exposure_program", length = 0)
	public String getExposureProgram() {
		return this.exposureProgram;
	}

	public void setExposureProgram(String exposureProgram) {
		this.exposureProgram = exposureProgram;
	}

	@Column(name = "date_time_original", length = 0)
	public String getDateTimeOriginal() {
		return this.dateTimeOriginal;
	}

	public void setDateTimeOriginal(String dateTimeOriginal) {
		this.dateTimeOriginal = dateTimeOriginal;
	}

	@Column(name = "exposure_compenstation", length = 0)
	public String getExposureCompenstation() {
		return this.exposureCompenstation;
	}

	public void setExposureCompenstation(String exposureCompenstation) {
		this.exposureCompenstation = exposureCompenstation;
	}

	@Column(name = "metering_mode", length = 0)
	public String getMeteringMode() {
		return this.meteringMode;
	}

	public void setMeteringMode(String meteringMode) {
		this.meteringMode = meteringMode;
	}

	@Column(name = "white_balance", length = 0)
	public String getWhiteBalance() {
		return this.whiteBalance;
	}

	public void setWhiteBalance(String whiteBalance) {
		this.whiteBalance = whiteBalance;
	}

	@Column(name = "lens_info", length = 0)
	public String getLensInfo() {
		return this.lensInfo;
	}

	public void setLensInfo(String lensInfo) {
		this.lensInfo = lensInfo;
	}

	@Column(name = "lens_model", length = 0)
	public String getLensModel() {
		return this.lensModel;
	}

	public void setLensModel(String lensModel) {
		this.lensModel = lensModel;
	}

	@Column(name = "lens_make", length = 0)
	public String getLensMake() {
		return this.lensMake;
	}

	public void setLensMake(String lensMake) {
		this.lensMake = lensMake;
	}

	@Column(name = "yresolution")
	public Integer getYresolution() {
		return this.yresolution;
	}

	public void setYresolution(Integer yresolution) {
		this.yresolution = yresolution;
	}

	@Column(name = "xresolution")
	public Integer getXresolution() {
		return this.xresolution;
	}

	public void setXresolution(Integer xresolution) {
		this.xresolution = xresolution;
	}

	@Column(name = "resolution_unit", length = 0)
	public String getResolutionUnit() {
		return this.resolutionUnit;
	}

	public void setResolutionUnit(String resolutionUnit) {
		this.resolutionUnit = resolutionUnit;
	}

	@Column(name = "orientation_desc")
	public String getOrientationDesc() {
		return this.orientationDesc;
	}

	public void setOrientationDesc(String orientation) {
		this.orientationDesc = orientation;
	}

	@Column(name = "focal_length", length = 32)
	public String getFocalLength() {
		return this.focalLength;
	}

	public void setFocalLength(String focalLength) {
		this.focalLength = focalLength;
	}
	
}
